### ISSUE TITLE
Solution to level 5?

### ISSUE THREAD

**Issue by Niknight** [md5crypt/clipsgame#3]
To achieve (contains inn traveler), the first rule is needed.
However, when reach (contains village traveler), the assassin is either in the inn or somewhere else that is connected with the village. For the first case, when I add fact(move traveler), the rule "watchout-for-assassins" will be activated and the fact (contains inn traveler) retracted. For the second case, the fact(move traveler) will move the traveler to the same place where assassin was sent to earlier.
Is there really a solution to this game? I'm desperate to know!

**Comment by md5crypt** [comment]
**two assertions**, if that doesn't help you send me a email, I just added contact info in the readme.
